-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintCoLa.

module Parser.PrintCoLa where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Parser.AbsCoLa

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Parser.AbsCoLa.Ident where
  prt _ (Parser.AbsCoLa.Ident i) = doc $ showString i
instance Print Parser.AbsCoLa.Contract where
  prt i = \case
    Parser.AbsCoLa.ConEmpty -> prPrec i 0 (concatD [])
    Parser.AbsCoLa.ConComp component -> prPrec i 0 (concatD [prt 0 component])
    Parser.AbsCoLa.ConAnd component contract -> prPrec i 0 (concatD [prt 0 component, doc (showString "C-AND"), prt 0 contract])

instance Print Parser.AbsCoLa.Component where
  prt i = \case
    Parser.AbsCoLa.ComDef definition -> prPrec i 0 (concatD [prt 0 definition])
    Parser.AbsCoLa.ComConDef conditionaldefinition -> prPrec i 0 (concatD [prt 0 conditionaldefinition])
    Parser.AbsCoLa.ComState statement -> prPrec i 0 (concatD [prt 0 statement])
    Parser.AbsCoLa.ComConState conditionalstatement -> prPrec i 0 (concatD [prt 0 conditionalstatement])

instance Print Parser.AbsCoLa.Definition where
  prt i = \case
    Parser.AbsCoLa.DefSim simpledefinition -> prPrec i 0 (concatD [prt 0 simpledefinition])
    Parser.AbsCoLa.DefAnd simpledefinition definition -> prPrec i 0 (concatD [prt 0 simpledefinition, doc (showString "AND"), prt 0 definition])

instance Print Parser.AbsCoLa.SimpleDefinition where
  prt i = \case
    Parser.AbsCoLa.SimDefIs id_ subject1 subject2 -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject1, doc (showString "IS"), prt 0 subject2])
    Parser.AbsCoLa.SimDefEq id_ subject numericalexpression -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, doc (showString "EQUALS"), prt 0 numericalexpression])
    Parser.AbsCoLa.SimDefDate id_ subject num1 month num2 -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, doc (showString "IS"), prt 0 num1, prt 0 month, prt 0 num2])

instance Print Parser.AbsCoLa.NumericalExpression where
  prt i = \case
    Parser.AbsCoLa.NumExpNum num -> prPrec i 0 (concatD [prt 0 num])
    Parser.AbsCoLa.NumExpObj numericalobject -> prPrec i 0 (concatD [prt 0 numericalobject])
    Parser.AbsCoLa.NumExpOp numericalexpression1 operator numericalexpression2 -> prPrec i 0 (concatD [prt 0 numericalexpression1, prt 0 operator, prt 0 numericalexpression2])

instance Print Parser.AbsCoLa.Operator where
  prt i = \case
    Parser.AbsCoLa.OpPlus -> prPrec i 0 (concatD [doc (showString "PLUS")])
    Parser.AbsCoLa.OpMin -> prPrec i 0 (concatD [doc (showString "MINUS")])
    Parser.AbsCoLa.OpMult -> prPrec i 0 (concatD [doc (showString "TIMES")])
    Parser.AbsCoLa.OpDiv -> prPrec i 0 (concatD [doc (showString "DIVIDE")])

instance Print Parser.AbsCoLa.ConditionalDefinition where
  prt i = \case
    Parser.AbsCoLa.ConDefIf definition condition -> prPrec i 0 (concatD [prt 0 definition, doc (showString "IF"), prt 0 condition])
    Parser.AbsCoLa.ConDefIfThen condition definition -> prPrec i 0 (concatD [doc (showString "IF"), prt 0 condition, doc (showString "THEN"), prt 0 definition])
    Parser.AbsCoLa.ConDefIfElse definition1 condition definition2 -> prPrec i 0 (concatD [prt 0 definition1, doc (showString "IF"), prt 0 condition, doc (showString "ELSE"), prt 0 definition2])
    Parser.AbsCoLa.ConDefIfThenElse condition definition1 definition2 -> prPrec i 0 (concatD [doc (showString "IF"), prt 0 condition, doc (showString "THEN"), prt 0 definition1, doc (showString "ELSE"), prt 0 definition2])

instance Print Parser.AbsCoLa.Statement where
  prt i = \case
    Parser.AbsCoLa.StateSim simplestatement -> prPrec i 0 (concatD [prt 0 simplestatement])
    Parser.AbsCoLa.StateOr simplestatement statement -> prPrec i 0 (concatD [prt 0 simplestatement, doc (showString "OR"), prt 0 statement])
    Parser.AbsCoLa.StateAnd simplestatement statement -> prPrec i 0 (concatD [prt 0 simplestatement, doc (showString "AND"), prt 0 statement])

instance Print Parser.AbsCoLa.ConditionalStatement where
  prt i = \case
    Parser.AbsCoLa.ConStateIf statement condition -> prPrec i 0 (concatD [prt 0 statement, doc (showString "IF"), prt 0 condition])
    Parser.AbsCoLa.ConStateIfThen condition statement -> prPrec i 0 (concatD [doc (showString "IF"), prt 0 condition, doc (showString "THEN"), prt 0 statement])
    Parser.AbsCoLa.ConStateIfElse statement1 condition statement2 -> prPrec i 0 (concatD [prt 0 statement1, doc (showString "IF"), prt 0 condition, doc (showString "ELSE"), prt 0 statement2])
    Parser.AbsCoLa.ConStateIfThenElse condition statement1 statement2 -> prPrec i 0 (concatD [doc (showString "IF"), prt 0 condition, doc (showString "THEN"), prt 0 statement1, doc (showString "ELSE"), prt 0 statement2])

instance Print Parser.AbsCoLa.SimpleStatement where
  prt i = \case
    Parser.AbsCoLa.SimStateOne id_ holds subject modalverb verb object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 subject, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver, prt 0 date])
    Parser.AbsCoLa.SimStateTwo id_ holds subject date modalverb verb object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 subject, prt 0 date, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimStateThree id_ holds date subject modalverb verb object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 date, prt 0 subject, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimStateFour id_ holds subject verbstatus object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 subject, prt 0 verbstatus, prt 0 object, prt 0 receiver, prt 0 date])
    Parser.AbsCoLa.SimStateOneNH id_ subject modalverb verb object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver, prt 0 date])
    Parser.AbsCoLa.SimStateTwoNH id_ subject date modalverb verb object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, prt 0 date, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimStateThreeNH id_ date subject modalverb verb object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 date, prt 0 subject, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimStateFourNH id_ subject verbstatus object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, prt 0 verbstatus, prt 0 object, prt 0 receiver, prt 0 date])

instance Print Parser.AbsCoLa.Condition where
  prt i = \case
    Parser.AbsCoLa.CondiSim simplecondition -> prPrec i 0 (concatD [prt 0 simplecondition])
    Parser.AbsCoLa.CondiOr simplecondition condition -> prPrec i 0 (concatD [prt 0 simplecondition, doc (showString "OR"), prt 0 condition])
    Parser.AbsCoLa.CondiAnd simplecondition condition -> prPrec i 0 (concatD [prt 0 simplecondition, doc (showString "AND"), prt 0 condition])

instance Print Parser.AbsCoLa.SimpleCondition where
  prt i = \case
    Parser.AbsCoLa.SimConOne id_ holds subject verbstatus object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 subject, prt 0 verbstatus, prt 0 object, prt 0 receiver, prt 0 date])
    Parser.AbsCoLa.SimConTwo id_ holds subject date verbstatus object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 subject, prt 0 date, prt 0 verbstatus, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimConThree id_ holds date subject verbstatus object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 date, prt 0 subject, prt 0 verbstatus, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimConFour id_ holds subject modalverb verb object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 subject, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver, prt 0 date])
    Parser.AbsCoLa.SimConFive id_ holds booleanexpression -> prPrec i 0 (concatD [prt 0 id_, prt 0 holds, prt 0 booleanexpression])
    Parser.AbsCoLa.SimConOneNH id_ subject verbstatus object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, prt 0 verbstatus, prt 0 object, prt 0 receiver, prt 0 date])
    Parser.AbsCoLa.SimConTwoNH id_ subject date verbstatus object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, prt 0 date, prt 0 verbstatus, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimConThreeNH id_ date subject verbstatus object receiver -> prPrec i 0 (concatD [prt 0 id_, prt 0 date, prt 0 subject, prt 0 verbstatus, prt 0 object, prt 0 receiver])
    Parser.AbsCoLa.SimConFourNH id_ subject modalverb verb object receiver date -> prPrec i 0 (concatD [prt 0 id_, prt 0 subject, prt 0 modalverb, prt 0 verb, prt 0 object, prt 0 receiver, prt 0 date])
    Parser.AbsCoLa.SimConFiveNH id_ booleanexpression -> prPrec i 0 (concatD [prt 0 id_, prt 0 booleanexpression])

instance Print Parser.AbsCoLa.BooleanExpression where
  prt i = \case
    Parser.AbsCoLa.BoolEx subject1 verbstatus comparison subject2 -> prPrec i 0 (concatD [prt 0 subject1, prt 0 verbstatus, prt 0 comparison, prt 0 subject2])

instance Print Parser.AbsCoLa.ID where
  prt i = \case
    Parser.AbsCoLa.IDSim num -> prPrec i 0 (concatD [doc (showString "["), prt 0 num, doc (showString "]")])
    Parser.AbsCoLa.IDRep num1 num2 -> prPrec i 0 (concatD [doc (showString "["), prt 0 num1, doc (showString "("), prt 0 num2, doc (showString ")"), doc (showString "]")])

instance Print Parser.AbsCoLa.Holds where
  prt i = \case
    Parser.AbsCoLa.HoldYes -> prPrec i 0 (concatD [doc (showString "it"), doc (showString "is"), doc (showString "the"), doc (showString "case"), doc (showString "that")])
    Parser.AbsCoLa.HoldNo -> prPrec i 0 (concatD [doc (showString "it"), doc (showString "is"), doc (showString "not"), doc (showString "the"), doc (showString "case"), doc (showString "that")])

instance Print Parser.AbsCoLa.Subject where
  prt i = \case
    Parser.AbsCoLa.SubQuoted str -> prPrec i 0 (concatD [printString str])
    Parser.AbsCoLa.SubUnQuoted id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print Parser.AbsCoLa.Verb where
  prt i = \case
    Parser.AbsCoLa.VDel -> prPrec i 0 (concatD [doc (showString "deliver")])
    Parser.AbsCoLa.VPay -> prPrec i 0 (concatD [doc (showString "pay")])
    Parser.AbsCoLa.VCharge -> prPrec i 0 (concatD [doc (showString "charge")])
    Parser.AbsCoLa.VRefund -> prPrec i 0 (concatD [doc (showString "refund")])

instance Print Parser.AbsCoLa.VerbStatus where
  prt i = \case
    Parser.AbsCoLa.VSDel -> prPrec i 0 (concatD [doc (showString "delivered")])
    Parser.AbsCoLa.VSPay -> prPrec i 0 (concatD [doc (showString "paid")])
    Parser.AbsCoLa.VSCharge -> prPrec i 0 (concatD [doc (showString "charged")])
    Parser.AbsCoLa.VSRefund -> prPrec i 0 (concatD [doc (showString "refunded")])

instance Print Parser.AbsCoLa.Comparison where
  prt i = \case
    Parser.AbsCoLa.CompareLess -> prPrec i 0 (concatD [doc (showString "less"), doc (showString "than")])
    Parser.AbsCoLa.CompareEq equal -> prPrec i 0 (concatD [prt 0 equal])
    Parser.AbsCoLa.CompareMore more -> prPrec i 0 (concatD [prt 0 more])

instance Print Parser.AbsCoLa.Equal where
  prt i = \case
    Parser.AbsCoLa.EqOne -> prPrec i 0 (concatD [doc (showString "equals")])
    Parser.AbsCoLa.EqTwo -> prPrec i 0 (concatD [doc (showString "equal"), doc (showString "to")])

instance Print Parser.AbsCoLa.More where
  prt i = \case
    Parser.AbsCoLa.MoreOne -> prPrec i 0 (concatD [doc (showString "more"), doc (showString "than")])
    Parser.AbsCoLa.MoreTwo -> prPrec i 0 (concatD [doc (showString "greater"), doc (showString "than")])

instance Print Parser.AbsCoLa.ModalVerb where
  prt i = \case
    Parser.AbsCoLa.ModalObli obligation -> prPrec i 0 (concatD [prt 0 obligation])
    Parser.AbsCoLa.ModalPermi -> prPrec i 0 (concatD [doc (showString "may")])
    Parser.AbsCoLa.ModalForbi -> prPrec i 0 (concatD [doc (showString "is"), doc (showString "forbidden"), doc (showString "to")])

instance Print Parser.AbsCoLa.Obligation where
  prt i = \case
    Parser.AbsCoLa.ObliOne -> prPrec i 0 (concatD [doc (showString "shall")])
    Parser.AbsCoLa.ObliTwo -> prPrec i 0 (concatD [doc (showString "must")])

instance Print Parser.AbsCoLa.Date where
  prt i = \case
    Parser.AbsCoLa.DateSpe specificdate -> prPrec i 0 (concatD [prt 0 specificdate])
    Parser.AbsCoLa.DateAny -> prPrec i 0 (concatD [doc (showString "on"), doc (showString "ANYDATE")])
    Parser.AbsCoLa.DateSome subject -> prPrec i 0 (concatD [doc (showString "on"), doc (showString "SOMEDATE"), prt 0 subject])
    Parser.AbsCoLa.DateThe subject -> prPrec i 0 (concatD [doc (showString "on"), doc (showString "THEDATE"), prt 0 subject])
    Parser.AbsCoLa.DateQuanSpecific temporalquantifier num1 month num2 -> prPrec i 0 (concatD [prt 0 temporalquantifier, prt 0 num1, prt 0 month, prt 0 num2])
    Parser.AbsCoLa.DateQuanSome temporalquantifier subject -> prPrec i 0 (concatD [prt 0 temporalquantifier, doc (showString "SOMEDATE"), prt 0 subject])
    Parser.AbsCoLa.DateQuanThe temporalquantifier subject -> prPrec i 0 (concatD [prt 0 temporalquantifier, doc (showString "THEDATE"), prt 0 subject])
    Parser.AbsCoLa.DateQuanSomeWO temporaloffset temporalquantifier subject -> prPrec i 0 (concatD [prt 0 temporaloffset, prt 0 temporalquantifier, doc (showString "SOMEDATE"), prt 0 subject])
    Parser.AbsCoLa.DateQuanTheWO temporaloffset temporalquantifier subject -> prPrec i 0 (concatD [prt 0 temporaloffset, prt 0 temporalquantifier, doc (showString "THEDATE"), prt 0 subject])
    Parser.AbsCoLa.DateQuanTempSome temporalquantifier1 temporaloffset temporalquantifier2 subject -> prPrec i 0 (concatD [prt 0 temporalquantifier1, prt 0 temporaloffset, prt 0 temporalquantifier2, doc (showString "SOMEDATE"), prt 0 subject])
    Parser.AbsCoLa.DateQuanTempThe temporalquantifier1 temporaloffset temporalquantifier2 subject -> prPrec i 0 (concatD [prt 0 temporalquantifier1, prt 0 temporaloffset, prt 0 temporalquantifier2, doc (showString "THEDATE"), prt 0 subject])

instance Print Parser.AbsCoLa.SpecificDate where
  prt i = \case
    Parser.AbsCoLa.DateSpeOnThe num1 month num2 -> prPrec i 0 (concatD [doc (showString "on"), doc (showString "the"), prt 0 num1, prt 0 month, prt 0 num2])
    Parser.AbsCoLa.DateSpeOn num1 month num2 -> prPrec i 0 (concatD [doc (showString "on"), prt 0 num1, prt 0 month, prt 0 num2])

instance Print Parser.AbsCoLa.TemporalQuantifier where
  prt i = \case
    Parser.AbsCoLa.TempAfter -> prPrec i 0 (concatD [doc (showString "after")])
    Parser.AbsCoLa.TempBefore -> prPrec i 0 (concatD [doc (showString "before")])

instance Print Parser.AbsCoLa.TemporalOffset where
  prt i = \case
    Parser.AbsCoLa.TempOffDay num -> prPrec i 0 (concatD [prt 0 num, doc (showString "day")])
    Parser.AbsCoLa.TempOffYear num -> prPrec i 0 (concatD [prt 0 num, doc (showString "year")])
    Parser.AbsCoLa.TempOffWeek num -> prPrec i 0 (concatD [prt 0 num, doc (showString "week")])
    Parser.AbsCoLa.TempOffDays num -> prPrec i 0 (concatD [prt 0 num, doc (showString "days")])
    Parser.AbsCoLa.TempOffYears num -> prPrec i 0 (concatD [prt 0 num, doc (showString "years")])
    Parser.AbsCoLa.TempOffWeeks num -> prPrec i 0 (concatD [prt 0 num, doc (showString "weeks")])

instance Print Parser.AbsCoLa.Month where
  prt i = \case
    Parser.AbsCoLa.MJan -> prPrec i 0 (concatD [doc (showString "January")])
    Parser.AbsCoLa.MFeb -> prPrec i 0 (concatD [doc (showString "February")])
    Parser.AbsCoLa.MMar -> prPrec i 0 (concatD [doc (showString "March")])
    Parser.AbsCoLa.MApr -> prPrec i 0 (concatD [doc (showString "April")])
    Parser.AbsCoLa.MMay -> prPrec i 0 (concatD [doc (showString "May")])
    Parser.AbsCoLa.MJun -> prPrec i 0 (concatD [doc (showString "June")])
    Parser.AbsCoLa.MJul -> prPrec i 0 (concatD [doc (showString "July")])
    Parser.AbsCoLa.MAug -> prPrec i 0 (concatD [doc (showString "August")])
    Parser.AbsCoLa.MSep -> prPrec i 0 (concatD [doc (showString "September")])
    Parser.AbsCoLa.MOct -> prPrec i 0 (concatD [doc (showString "October")])
    Parser.AbsCoLa.MNov -> prPrec i 0 (concatD [doc (showString "November")])
    Parser.AbsCoLa.MDec -> prPrec i 0 (concatD [doc (showString "December")])

instance Print Parser.AbsCoLa.Object where
  prt i = \case
    Parser.AbsCoLa.ObjNu numericalobject -> prPrec i 0 (concatD [prt 0 numericalobject])
    Parser.AbsCoLa.ObjNonNu nonnumericalobject -> prPrec i 0 (concatD [prt 0 nonnumericalobject])

instance Print Parser.AbsCoLa.NumericalObject where
  prt i = \case
    Parser.AbsCoLa.NumPound pounds num -> prPrec i 0 (concatD [prt 0 pounds, prt 0 num])
    Parser.AbsCoLa.NumDol dollars num -> prPrec i 0 (concatD [prt 0 dollars, prt 0 num])
    Parser.AbsCoLa.NumEur euros num -> prPrec i 0 (concatD [prt 0 euros, prt 0 num])
    Parser.AbsCoLa.NumAmount subject -> prPrec i 0 (concatD [doc (showString "AMOUNT"), prt 0 subject])

instance Print Parser.AbsCoLa.Pounds where
  prt i = \case
    Parser.AbsCoLa.PoundOne -> prPrec i 0 (concatD [doc (showString "GBP")])
    Parser.AbsCoLa.PoundTwo -> prPrec i 0 (concatD [doc (showString "POUNDS")])
    Parser.AbsCoLa.PoundThree -> prPrec i 0 (concatD [doc (showString "quid")])

instance Print Parser.AbsCoLa.Dollars where
  prt i = \case
    Parser.AbsCoLa.DollarOne -> prPrec i 0 (concatD [doc (showString "USD")])
    Parser.AbsCoLa.DollarTwo -> prPrec i 0 (concatD [doc (showString "DOLLARS")])
    Parser.AbsCoLa.DollarThree -> prPrec i 0 (concatD [doc (showString "buck")])

instance Print Parser.AbsCoLa.Euros where
  prt i = \case
    Parser.AbsCoLa.EuroOne -> prPrec i 0 (concatD [doc (showString "EUR")])
    Parser.AbsCoLa.EuroTwo -> prPrec i 0 (concatD [doc (showString "EUROS")])

instance Print Parser.AbsCoLa.NonNumericalObject where
  prt i = \case
    Parser.AbsCoLa.NonNumCurr subject -> prPrec i 0 (concatD [doc (showString "SOMECURRENCY"), prt 0 subject])
    Parser.AbsCoLa.NonNumRep subject -> prPrec i 0 (concatD [doc (showString "REPORT"), prt 0 subject])
    Parser.AbsCoLa.NonNumNamed subject -> prPrec i 0 (concatD [doc (showString "NAMEDOBJECT"), prt 0 subject])
    Parser.AbsCoLa.NonNumOther subject -> prPrec i 0 (concatD [doc (showString "OTHEROBJECT"), prt 0 subject])

instance Print Parser.AbsCoLa.Num where
  prt i = \case
    Parser.AbsCoLa.NumInt n -> prPrec i 0 (concatD [prt 0 n])

instance Print Parser.AbsCoLa.Receiver where
  prt i = \case
    Parser.AbsCoLa.Rec subject -> prPrec i 0 (concatD [doc (showString "to"), prt 0 subject])
